version: "3.5"
services:
  spring-boot:
    image: spring-boot
    build:
      context: .
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_HIBERNATE_OPTION=create
    ports:
      - "8080:8080"
      - "5005:5005"
